<?php namespace iAmirNet\HesabFa;

use App;
use Auth;
use Azarinweb\User\Controllers\Users as UsersController;
use Azarinweb\Minimall\Controllers\Products as ProductsController;
use Azarinweb\Minimall\Controllers\Orders as OrdersController;
use Azarinweb\User\Models\User as UserModel;
use Azarinweb\Minimall\Models\Product as ProductModel;
use Azarinweb\Minimall\Models\Order as OrderModel;
use iAmirNet\HesabFa\Models\HesabFaSettings;
use iAmirNet\HesabFa\Updates\OrderAddHesabfaCodeField;
use iAmirNet\HesabFa\Updates\ProductAddHesabfaCodeField;
use iAmirNet\HesabFa\Updates\UserAddHesabfaCodeField;
use Event;
use Yaml;
use File;
use Backend;
use System\Classes\PluginBase;

require_once "updates/order_add_hesabfa_code_field.php";
require_once "updates/product_add_hesabfa_code_field.php";
require_once "updates/user_add_hesabfa_code_field.php";

class Plugin extends PluginBase
{
    /**
     * @var boolean Determine if this plugin should have elevated privileges.
     */
    public $elevated = true;

    public function pluginDetails()
    {
        return [
            'name'        => 'iamirnet.hesabfa::lang.plugin.name',
            'description' => 'iamirnet.hesabfa::lang.plugin.description',
            'author'      => 'iamirnet',
            'icon'        => 'icon-user',
            'homepage'    => 'https://iAmir.Net'
        ];
    }

    public function boot()
    {
        $this->extendModels();
        $this->extendControllers();
        (new UserAddHesabfaCodeField())->up();
        (new ProductAddHesabfaCodeField())->up();
        (new OrderAddHesabfaCodeField())->up();
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function registerPermissions()
    {
        return [
            'iamirnet.hesabfa.access_hesabfa' => [
                'tab'   => 'iamirnet.hesabfa::lang.plugin.tab',
                'label' => 'iamirnet.hesabfa::lang.plugin.access_hesabfa'
            ],
        ];
    }

    public function registerSettings()
    {
        return [
            'settings' => [
                'label'       => 'iamirnet.hesabfa::lang.hesabfa.title',
                'description' => 'iamirnet.hesabfa::lang.hesabfa.description',
                'category'    => 'iamirnet.minimall::lang.settings.accounting.title',
                'icon'        => 'icon-credit-card',
                'class'       => HesabFaSettings::class,
                'order'       => 800,
                'permissions' => ['iamirnet.hesabfa.access_hesabfa']
            ]
        ];
    }
    protected function extendModels()
    {
        UserModel::extend(function($model) {
            $model->addFillable([
                'hesabfa_code',
            ]);
        });
        ProductModel::extend(function($model) {
            $model->addFillable([
                'hesabfa_code',
            ]);
        });
        OrderModel::extend(function($model) {
            $model->addFillable([
                'hesabfa_code',
            ]);
        });
    }

    protected function extendControllers()
    {
        UsersController::extendFormFields(function($widget) {
            if (!$widget->model instanceof UserModel) return;
            $configFile = plugins_path('iamirnet/hesabfa/config/user_extra_fields.yaml');
            $config = Yaml::parse(File::get($configFile));
            $widget->addTabFields($config);
        });
        ProductsController::extendFormFields(function($widget) {
            if (!$widget->model instanceof ProductModel) return;
            $configFile = plugins_path('iamirnet/hesabfa/config/product_extra_fields.yaml');
            $config = Yaml::parse(File::get($configFile));
            $widget->addTabFields($config);
        });
    }


}
